name: bloc_architecture_app
description: A Flutetr Bloc Architecture project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  cupertino_icons: ^1.0.0
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  parse_server_sdk_flutter: ^3.1.0
  image_picker: ^0.8.3+3
  gallery_saver: ^2.1.3
  grouped_buttons: ^1.0.4
  url_launcher: ^6.0.9
  http: any
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
      
